#!/usr/bin/perl

my $defl_enabled = 0;
my $defl_level = 10;
for my $arg (@ARGV) {
    if($arg =~ /^-defl(?::(\d+))?$/) {
        $defl_enabled = 1;
        if(defined($1)) {
            $defl_level = $1;
        }
    }
}

if($defl_enabled) {
    if($defl_level < 0) {
        $defl_level = 0;
    }
    if($defl_level > 9) {
        $defl_level = 9;
    }
    eval {
        require Compress::Zlib;
        Compress::Zlib->import();
    };
    if($@) {
        die "ERROR: -defl requested but Compress::Zlib is not available: $@";
    }
}

open(OUTPUT, "> fsdata_custom.c");

chdir("pages");
open(FILES, "find . -type f |");

while($file = <FILES>) {

    # Do not include files in CVS directories nor backup files.
    if($file =~ /(CVS|~)/) {
    	next;
    }
    
    chop($file);
    
    my $include_header = !($file =~ /\.plain$/ || $file =~ /cgi/);
    my $is_text_file = ($file =~ /\.(s?html?|css|js|txt|xml)$/i);
    my $is_ssi_file = ($file =~ /\.(shtml|shtm|ssi)$/i);
    my $is_already_compressed = ($file =~ /\.(png|jpe?g|gif|zip|gz|bz2|mp3|mp4|avi|mov|woff2?|pdf)$/i);
    my $strip_whitespace = $is_text_file;
    my $is_compressed = 0;
    my $body = "";

    if($strip_whitespace) {
	open(SRC, $file) || die $!;
	while($line = <SRC>) {
	    $line =~ s/^\s+//;
	    $line =~ s/\s+$//;
	    $body .= "$line\n";
	}
	close(SRC);
    } else {
	open(SRC, $file) || die $!;
	binmode(SRC);
	while(read(SRC, $data, 4096)) {
	    $body .= $data;
	}
	close(SRC);
    }

    if($defl_enabled && $include_header && !$is_ssi_file && !$is_already_compressed && length($body) > 0) {
	my $deflated = Compress::Zlib::compress($body, $defl_level);
	if(defined($deflated) && length($deflated) < length($body)) {
	    $body = $deflated;
	    $is_compressed = 1;
	}
    }

    open(TEMP, "> /tmp/file") || die $!;
    binmode(TEMP);
    if($include_header) {
	if($file =~ /404/) {
	    print(TEMP "HTTP/1.0 404 File not found\r\n");
	} else {
	    print(TEMP "HTTP/1.0 200 OK\r\n");
	}
	print(TEMP "Server: lwIP/pre-0.6 (http://www.sics.se/~adam/lwip/)\r\n");
	if($file =~ /\.s?html?$/) {
	    print(TEMP "Content-type: text/html\r\n");
	} elsif($file =~ /\.gif$/) {
	    print(TEMP "Content-type: image/gif\r\n");
	} elsif($file =~ /\.png$/) {
	    print(TEMP "Content-type: image/png\r\n");
	} elsif($file =~ /\.jpg$/) {
	    print(TEMP "Content-type: image/jpeg\r\n");
	} elsif($file =~ /\.class$/) {
	    print(TEMP "Content-type: application/octet-stream\r\n");
	} elsif($file =~ /\.ram$/) {
	    print(TEMP "Content-type: audio/x-pn-realaudio\r\n");
	} else {
	    print(TEMP "Content-type: text/plain\r\n");
	}
	if($is_compressed) {
	    print(TEMP "Content-Encoding: deflate\r\n");
	}
	print(TEMP "\r\n");
    }
    print(TEMP $body);
    close(TEMP);
    
    open(FILE, "/tmp/file");
    unlink("/tmp/file");

    $file =~ s/\.//;
    $fvar = $file;
    $fvar =~ s-/-_-g;
    $fvar =~ s-\.-_-g;
    print(OUTPUT "static const unsigned char data".$fvar."[] = {\n");
    print(OUTPUT "\t/* $file */\n\t");
    for($j = 0; $j < length($file); $j++) {
	printf(OUTPUT "%#02x, ", unpack("C", substr($file, $j, 1)));
    }
    printf(OUTPUT "0,\n");
    
    
    $i = 0;
    while(read(FILE, $data, 1)) {
        if($i == 0) {
            print(OUTPUT "\t");
        }
        printf(OUTPUT "%#02x, ", unpack("C", $data));
        $i++;
        if($i == 10) {
            print(OUTPUT "\n");
            $i = 0;
        }
    }
    print(OUTPUT "};\n\n");
    close(FILE);
    push(@fvars, $fvar);
    push(@files, $file);
}

for($i = 0; $i < @fvars; $i++) {
    $file = $files[$i];
    $fvar = $fvars[$i];

    if($i == 0) {
        $prevfile = "NULL";
    } else {
        $prevfile = "file" . $fvars[$i - 1];
    }
    print(OUTPUT "const struct fsdata_file file".$fvar."[] = {{$prevfile, data$fvar, ");
    print(OUTPUT "data$fvar + ". (length($file) + 1) .", ");
    print(OUTPUT "sizeof(data$fvar) - ". (length($file) + 1) .", FS_FILE_FLAGS_HEADER_INCLUDED | FS_FILE_FLAGS_HEADER_PERSISTENT}};\n\n");
}

print(OUTPUT "#define FS_ROOT file$fvars[$i - 1]\n\n");
print(OUTPUT "#define FS_NUMFILES $i\n");
