name: test

on: 
  push: { branches: [ integration, main, ci_cd_pipeline ] }
  pull_request:  { branches: [ main ] }
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-24.04

    steps:
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake gcc make clang-format-18

    - name: Show clang-format version
      run: clang-format-18 --version

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Init required submodules
      run: |
        git submodule sync --recursive
        git submodule update --init --recursive libs/coreJSON
        git submodule update --init --depth 1 libs/STM32_HAL/STM32H7
        git -C libs/STM32_HAL/STM32H7 submodule update --init --recursive --depth 1 Drivers/BSP/STM32H7xx_Nucleo
        git -C libs/STM32_HAL/STM32H7 submodule update --init --recursive --depth 1 Drivers/BSP/Components/lan8742
        git -C libs/STM32_HAL/STM32H7 submodule update --init --recursive --depth 1 Drivers/CMSIS/Device/ST/STM32H7xx
        git -C libs/STM32_HAL/STM32H7 submodule update --init --recursive --depth 1 Drivers/BSP/Components/Common

    - name: Configure with CMake
      run: cmake -S tests -B build

    - name: Check formatting (clang-format)
      run: |
        find adapters app dev middleware platform tests -path 'dev/scripts/env' -prune -o -path '*/_deps' -prune -o -path '*/build' -prune -o -path '*/CMakeFiles' -prune -o -type f \( -name '*.c' -o -name '*.h' \) -print | awk 'NR==1{printf "%s",$0; next} {printf "\n%s",$0}' > tools/clang/clang_files.txt
        clang-format-18 -style=file --dry-run --Werror --files=./tools/clang/clang_files.txt

    - name: Build tests
      run: cmake --build build

    - name: Run tests with CTest
      run: ctest --test-dir build --output-on-failure
